spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/moview
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect